export default {
  "name": "style-snap-sorcery",
  "version": "2.0.0",
  "db_major_version": 15,
  "project_id": "style-snap-sorcery",
  "api": {
    "enabled": true,
    "port": 54321,
    "schemas": {
      "public": {
        "enabled": true,
        "max_rows": 1000
      },
      "graphql_public": {
        "enabled": true,
        "max_rows": 1000
      }
    },
    "extra_search_path": ["public", "extensions"],
    "max_rows": 1000
  },
  "db": {
    "port": 54322,
    "shadow_port": 54320,
    "major_version": 15
  },
  "realtime": {
    "enabled": false,
    "ip_version": "IPv6",
    "tenant_name": "realtime-dev"
  },
  "studio": {
    "enabled": true,
    "port": 54323,
    "api_url": "http://127.0.0.1"
  },
  "inbucket": {
    "enabled": true,
    "port": 54324,
    "api_port": 54325,
    "smtp_port": 54326
  },
  "storage": {
    "enabled": true,
    "file_size_limit": "50MiB",
    "buckets": {
      "user_uploads": {
        "public": false,
        "file_size_limit": "50MiB",
        "allowed_mime_types": ["image/*"]
      }
    }
  },
  "auth": {
    "enabled": true,
    "site_url": "http://127.0.0.1:3000",
    "additional_redirect_urls": ["https://127.0.0.1:3000"],
    "jwt_expiry": 3600,
    "enable_signup": true,
    "email": {
      "enable_signup": true,
      "double_confirm_changes": true,
      "enable_confirmations": false
    }
  },
  "edge_functions": {
    "enabled": true,
    "import_map": "./supabase/functions/import_map.json"
  },
  "analytics": {
    "enabled": false
  }
}